### ISSUE TITLE
How do I add search view to  toolbar based on you displayed list

### ISSUE THREAD

**Issue by devshisiyani** [android/uamp#130]
Great piece Music Player code.
of How can you search on a list based on list chosen. Eg rock, Jazz, pop,
I want user to be able to type in search bar and context browse fragment is searched.
Any help would be appreciated

**Comment by hnvn** [comment]
Take a look at method `getChildren(...)` in `MusicProvider` class where process queries from client (by calling `subscribe(..)` to `MediaBrowser`). In this method, the kind of query is detected by category value extract from mediaId such as: `MEDIA_ID_MUSICS_BY_GENRE`, `MEDIA_ID_MUSICS_BY_SEARCH`. You can use category `MEDIA_ID_MUSICS_BY_SEARCH` to perform search action from your client (Fragment, Activity) by attaching your query in mediaId like this:

 `String mediaId = MediaIDHelper.createMediaID(null, MEDIA_ID_MUSICS_BY_SEARCH, query);`

Add your code in `getChildren(...)` method to extract query from mediaId and perform your search from list of musics.

**Comment by Arrenign** [comment]
@hnvn Hey dude I've asked the same question in stack can you help me [Search Implimentation](https://stackoverflow.com/questions/48079968/how-to-implement-search-in-universal-music-player)

**Comment by hnvn** [comment]
I don't understand your matter. Which part do you get hard, UI or logic search implement?

**Comment by Arrenign** [comment]
@hnvn I don't get the whole thing ..Like before i've implimented search in my previous apps using recycler view and a getfilter() to filter out the searches but I see its not the same for this music player. To make it more simpler all i have now is the user interface in the menu xml (Search widget). Can you please explain to me how I'm supposed to set it to filter out the search results. Like if you have any spare time just give me on a step to step way to do it ...IF so It would be so much helpful cause I'm really new to android and have released only a few apps. and all the previous methods work just by filter search.

Thanks hnvn

**Comment by olehka** [comment]
@devshisiyani @Arrenign Hi, have you solved this question? I have similar problem. I want to filter (or search) by the whole hierarchy of media items. Thanks

**Comment by dturner** [comment]
Please ask questions on StackOverflow.
