### ISSUE TITLE
Multiple songs List by Genre 

### ISSUE THREAD

**Issue by rajendrachauhan** [android/uamp#166]
Hi 
   In genre category, To support multiple category in this player.
list of category:
Genre 1
Genre 2
Genre 3
like as display in BrowsFragment

**Comment by nic0lette** [comment]
Sorry, I'm not sure I understand? Can you provide a more concrete example of what you'd like to see?

**Comment by mrbankim** [comment]
Hi.. 
Right now in home page we have only one item Genres. So can we have multiple items and for that what will be the json structure.

**Comment by nic0lette** [comment]
Ah, thank you for explaining more.

Unfortunately there's nothing in the JSON itself that dictates how that works.

If you take a look at this part of the code: [MusicProvider.createBrowsableMediaItemForRoot](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java#L316) you can see where it makes the 'root', which consists of a single entry for "Genres".

To add other options you'd have to create a new entry in that method, and also create a new version of [MusicProvider.createBrowsableMediaItemForGenre](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java#L328) that can handle another way of browsing.

**Comment by mrbankim** [comment]
Hi @nic0lette 

Thank you for your quick reply. 
Can you give me some example of code for getting item like, In home page I should get 

Home page:

Item-1
Item-2 
Item-3

Once click on Item-1 I should get child item of Item-1 in 2nd page.

**Comment by dturner** [comment]
This isn't a priority at the moment.
