### ISSUE TITLE
Unable to advance to next or other song while playing to Chromecast Audio

### ISSUE THREAD

**Issue by ryanckim** [android/uamp#182]
Hi, I've noticed that when I'm playing a song on the list (from the default Google server) to Chromecast Audio and select another song on the list or try to skip to the next song, an error is thrown (see log below) about 5 times and it doesn't progress to the next or selected song.  Instead it just moves on to a random song on the list, or keeps playing the same song. This is with the code directly complied and run on a tablet, without any modification. Oh, and this does not happen when Chromecast is not being used. Can anyone please help? Thanks.

11-15 03:08:49.792 18204-18204/com.example.android.uamp E/MediaNotificationServiceImpl: Unregistering trampoline BroadcastReceiver failed
                                                                                        java.lang.IllegalArgumentException: Receiver not registered: yy@8f7a15d
                                                                                            at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:789)
                                                                                            at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1200)
                                                                                            at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
                                                                                            at yx.b(:com.google.android.gms.DynamiteModulesC@11746440:105)
                                                                                            at yp.onTransact(:com.google.android.gms.DynamiteModulesC@11746440:22)
                                                                                            at android.os.Binder.transact(Binder.java:392)
                                                                                            at com.google.android.gms.internal.zzed.zzb(Unknown Source)
                                                                                            at com.google.android.gms.cast.framework.media.zze.onDestroy(Unknown Source)
                                                                                            at com.google.android.gms.cast.framework.media.MediaNotificationService.onDestroy(Unknown Source)
                                                                                            at android.app.ActivityThread.handleStopService(ActivityThread.java:3244)
                                                                                            at android.app.ActivityThread.-wrap21(ActivityThread.java)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                            at android.os.Looper.loop(Looper.java:207)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by ryanckim** [comment]
I think I've found where the problem comes, but still haven't figured out what I can do...When I use Chromecast, CastPlayback class is used (as opposed to LocalPlayback), and when I play a song, 

`    public void play(QueueItem item) {
        try {
            loadMedia(item.getDescription().getMediaId(), true);
            mPlaybackState = PlaybackStateCompat.STATE_BUFFERING;
            if (mCallback != null) {
                mCallback.onPlaybackStatusChanged(mPlaybackState);
            }
        } catch (JSONException e) {
            LogHelper.e(TAG, "Exception loading media ", e, null);
            if (mCallback != null) {
                mCallback.onError(e.getMessage());
            }
        }
    }`

This calls loadMedia(...) which I believe will start playing the selected item by calling 

`        mRemoteMediaClient.load(media, autoPlay, mCurrentPosition, customData);   `

But after this runs once, it is somehow called again, along with multiple calls of these two methods

`private void setMetadataFromRemote() `
and
`private void updatePlaybackState()`

And when the player is about to start the new selected song, these repeated calls somehow reverts the mediaInfo back to the previous one, or switches them back and forth, continuously making the player switch songs before it starts playing anything. I don't know how this happens - is there a way to stop these multiple calls to these methods? Hopefully this will stop the odd behaviour. Please help!

**Comment by ryanckim** [comment]
I've updated Chromecast SDK and tried but see the same behaviour. I now use the new RemoteMediaClient.load method, inside CastPlayback.loadMedia method. Instead of 

`mRemoteMediaClient.load(media, autoPlay, mCurrentPosition, customData);`

which is deprecated, I use

`mRemoteMediaClient.load(media, new MediaLoadOptions.Builder()
                .setAutoplay(autoPlay)
                .setPlayPosition(mCurrentPosition)
                .setPlaybackRate(1)
                .setCustomData(customData)
                .build());`

This is called anytime a new track is selected (by myself selecting an arbitrary track, or automatically when the current song finishes). But through logging I've found that mRemoteMediaClient did not update its MediaInfo even after the above load method was called. In other words, let's say I was streaming the current music with 

mediaID=__BY_GENRE__/Mixed|556569945 to Chromecast.

The moment the next song is supposed to start (after the current song finishes), the above method is called again with the next mediaID, e.g., __BY_GENRE__/Mixed|-1313098574, and it seems to start. 

But when I retrieve the MediaInfo right after that line, by using 

`mRemoteMediaClient.getMediaInfo()`

it doesn't give me the new mediaID "__BY_GENRE__/Mixed|-1313098574", but somehow keeps the old one "__BY_GENRE__/Mixed|556569945".

And what's more, after this, PlaybackManager.handlePlayRequest() method is called again later (don't know why), inside which

`MediaSessionCompat.QueueItem currentMusic = mQueueManager.getCurrentMusic();`

this gives yet another track number on the list (neither of the above two songs). This consequently calls CastPlayback.loadMedia again and changes the track to be played.  That's what I have found so far.

I'm now curious about this RemoteMediaClient.load method. If I make it 

`PendingResult result = mRemoteMediaClient.load(media, new MediaLoadOptions.Builder()      
                .setAutoplay(autoPlay)
                .setPlayPosition(mCurrentPosition)
                .setPlaybackRate(1)
                .setCustomData(customData)
                .build());`

can I use this output to maybe check what's been done, and to make it wait until mediaInfo is updated? I don't see any example on how to use this PendingResult object. 

This seems like a bug to me, but am I the only one (of few) experiencing this issue? I've found another person having the same issue on the Google+ community. I'd really appreciate any help here!

**Comment by nic0lette** [comment]
Thank you for the report! We're looking into the problem.
Sorry about the delay.

**Comment by ryanckim** [comment]
Thanks. Here's my odd-looking temporary solution. Basically my problems were in 2 separate cases: 1) when I select a song myself while something else is playing, and 2) when one song finishes and tries to move on to the next song on the list. 

For 1) I modified **CastPlayback.setMetadataFromRemote()**

```Java

    private void setMetadataFromRemote() {
        // Sync: We get the customData from the remote media information and update the local
        // metadata if it happens to be different from the one we are currently using.
        // This can happen when the app was either restarted/disconnected + connected, or if the
        // app joins an existing session while the Chromecast was playing a queue.
        try {
            LogHelper.d(TAG, "Entered setMetadataFromRemote");
            MediaInfo mediaInfo = mRemoteMediaClient.getMediaInfo();
            if (mediaInfo == null) {
                return;
            }
            JSONObject customData = mediaInfo.getCustomData();

            if (customData != null && customData.has(ITEM_ID)) {
                String remoteMediaId = customData.getString(ITEM_ID);
                LogHelper.d(TAG, "Current Media Id:", mCurrentMediaId);
                LogHelper.d(TAG, "Remote Media Id:", remoteMediaId);
                if (!TextUtils.equals(mCurrentMediaId, remoteMediaId)) {
                    LogHelper.w(TAG, "Current and remote media IDs not equal");
                    // mCurrentMediaId = remoteMediaId;              // EVEN IF mCurrentMediaId has already been updated to the new selected item,
                                                                    // remoteMediaId does not seem to have been updated somehow, so this always
                                                                    // replaces the new selected item with old one (or some random one)
                    remoteMediaId = mCurrentMediaId;            // Current workaround is to simply disregard remoteMediaId
                                                                    // and to use mCurrentMediaId always (once updated on new item selection)
                    if (mCallback != null) {
                        mCallback.setCurrentMediaId(remoteMediaId);
                    }
                    updateLastKnownStreamPosition();
                }
            }
        } catch (JSONException e) {
            LogHelper.e(TAG, e, "Exception processing update metadata");
        }

    }
```

And for 2), I firstly modified **CastPlayback.updatePlaybackState()** - I used another variable named `mIdleReason` within `CastPlayback`, as another status checker, so that when `idleReason` is IDLE_REASON_FINISHED the `mCallback.onCompletion()` is not called multiple times. 

```Java

    private void updatePlaybackState() {
        int status = mRemoteMediaClient.getPlayerState();
        int idleReason = mRemoteMediaClient.getIdleReason();

        LogHelper.d(TAG, "Entered updatePlaybackState, PlayerState: ", status);
        LogHelper.d(TAG, "Entered updatePlaybackState, IdleReason: ", idleReason);

        // Convert the remote playback states to media playback states.
        switch (status) {
            case MediaStatus.PLAYER_STATE_IDLE:
                if (idleReason == MediaStatus.IDLE_REASON_FINISHED && mIdleReason == MediaStatus.IDLE_REASON_FINISHED) {
                    if (mCallback != null) {
                        mCallback.onCompletion();
                    }
                }
                break;
            case MediaStatus.PLAYER_STATE_BUFFERING:
                mPlaybackState = PlaybackStateCompat.STATE_BUFFERING;
                if (mCallback != null) {
                    mCallback.onPlaybackStatusChanged(mPlaybackState);
                    mIdleReason = MediaStatus.IDLE_REASON_FINISHED;
                }
                break;
            case MediaStatus.PLAYER_STATE_PLAYING:
                mPlaybackState = PlaybackStateCompat.STATE_PLAYING;
                LogHelper.d(TAG, "STATE PLAYING. Calling setMetadataFromRemote");
                setMetadataFromRemote();
                if (mCallback != null) {
                    mCallback.onPlaybackStatusChanged(mPlaybackState);
                    mIdleReason = MediaStatus.IDLE_REASON_FINISHED;
                }
                break;
            case MediaStatus.PLAYER_STATE_PAUSED:
                mPlaybackState = PlaybackStateCompat.STATE_PAUSED;
                LogHelper.d(TAG, "STATE PAUSED. Calling setMetadataFromRemote");
                setMetadataFromRemote();
                if (mCallback != null) {
                    mCallback.onPlaybackStatusChanged(mPlaybackState);
                }
                break;
            default: // case unknown
                LogHelper.d(TAG, "State default : ", status);
                break;
        }
    }
```

This `mIdleReason` is set and changed inside **CastPlayback.loadMedia(...)**  to IDLE_REASON_NONE, right after `mRemoteMediaClient.load(...)` is called:

```Java
    private void loadMedia(String mediaId, boolean autoPlay) throws JSONException {
        LogHelper.d(TAG, "Entered loadMedia, passed mediaId: " + mediaId);
        PendingResult result;
        String musicId = MediaIDHelper.extractMusicIDFromMediaID(mediaId);
        MediaMetadataCompat track = mMusicProvider.getMusic(musicId);   // returns the metadata of musicId item
        if (track == null) {
            throw new IllegalArgumentException("Invalid mediaId " + mediaId);
        }
        if (!TextUtils.equals(mediaId, mCurrentMediaId)) {
            mCurrentMediaId = mediaId;
            mCurrentPosition = 0;
        }
        JSONObject customData = new JSONObject();
        customData.put(ITEM_ID, mediaId);
        MediaInfo media = toCastMediaMetadata(track, customData);
        LogHelper.d(TAG, "Sending mediaInfo to mRemoteMediaClient");
        if (media != null)
            LogHelper.d(TAG, "media info thrown to mRemoteMediaClient:", media.getCustomData().getString(ITEM_ID));
//        mRemoteMediaClient.load(media, autoPlay, mCurrentPosition, customData);     // deprecated?
        result = mRemoteMediaClient.load(media, new MediaLoadOptions.Builder()       // THIS DOESN'T SEEM TO UPDATE THE mediaInfo RIGHT AWAY!!
                .setAutoplay(autoPlay)
                .setPlayPosition(mCurrentPosition)
                .setPlaybackRate(1)
//                .setActiveTrackIds()
                .setCustomData(customData)
                .build());
        LogHelper.d(TAG, "mRemoteMediaClient.load finished");

        mIdleReason = MediaStatus.IDLE_REASON_NONE;           // testing to ensure the load method runs only once
        if (mRemoteMediaClient.getMediaInfo() != null)
            LogHelper.d(TAG, "media info loaded inside mRemoteMediaClient:", mRemoteMediaClient.getMediaInfo().getCustomData().getString(ITEM_ID));
    }
```

This is my first ever Android project, so maybe this workaround doesn't look that elegant, but well, at least I've got it working as I expected. Hope this helps you to pinpoint the problems and perhaps to come up with a proper solution.

**Comment by Redwid** [comment]
I've got the same issue.
The temporary solution from @ryanckim works for me.

**Comment by maboueita** [comment]
Got the same issue too. Has been there any update on it?

**Comment by Redwid** [comment]
I do recommend this changes in QueueManager.java:
``
private int mCurrentIndex = -1;// Init to -1 

public QueueManager(@NonNull MusicProvider musicProvider,
                        @NonNull Resources resources,
                        @NonNull MetadataUpdateListener listener) {
        this.mMusicProvider = musicProvider;
        this.mListener = listener;
        this.mResources = resources;

        mPlayingQueue = Collections.synchronizedList(new ArrayList<MediaSessionCompat.QueueItem>());
        //mCurrentIndex = 0; //Remove this initialization
    }

    private void setCurrentQueueIndex(int index) {
        if (index >= 0 && index < mPlayingQueue.size()) {
            final boolean needsUpdate = mCurrentIndex != index; //Check if you need to call update
            mCurrentIndex = index;
            if(needsUpdate) {
                mListener.onCurrentQueueIndexUpdated(mCurrentIndex);
            }
        }
    }
``
It was a quite long time ago, but as I remember ... code constantly changed mCurrentIndex in this setCurrentQueueIndex() method ... from the listener possible.

**Comment by grennis** [comment]
This seems to still be a bug. The bug is that `updatePlaybackState` is called multiple times with state = idle, and idle reason = finished. The fix from @ryanckim may work for now, but it's relying on certain calls being called in certain order and probably will break when the fix is made... Is there a fix or workaround that doesn't rely on this?

**Comment by dturner** [comment]
Should be fixed with the addition of the ExoPlayer Cast extension.
