### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by dellagustin** [android/uamp#186]
As a newcomer with little Android SDK Knowledge, I find it hard to navigate through the code without a "map".

It would me nice to have some kind of documentation explaining the main blocks, entrypoints and relationships.

Linking to this talk would also help:
https://www.youtube.com/watch?v=iIKxyDRjecU

**Comment by nic0lette** [comment]
Hey! Thank you for your thoughts.

We're just getting started on work to improve this sample, and I'll keep your comments in mind as we do.

Thank you for the suggestion to link the I/O talk. I'll take a look to see where it would best fit in.

**Comment by nic0lette** [comment]
I've updated the documentation in the code quite a bit with the rewrite. I can understand how a map would help as well, so I'll try to work on something like that next.

**Comment by noname2534** [comment]
Good

**Comment by noname2534** [comment]
+1

**Comment by AndroidDeveloperLB** [comment]
@dellagustin Does this talk also include explanation of how to get songs from the actual storage?

**Comment by dturner** [comment]
Covered in the [FullGuide](https://github.com/android/uamp/blob/main/docs/FullGuide.md)
