### ISSUE TITLE
Add Cast/remote playback support

### ISSUE THREAD

**Issue by nic0lette** [android/uamp#222]
Add support for remote playback with the [Cast SDK](https://developers.google.com/cast/docs/developers) or [MediaRouter](https://developer.android.com/guide/topics/media/mediarouter)

**Comment by loki666** [comment]
why not https://github.com/google/ExoPlayer/tree/release-v2/extensions/cast ?

**Comment by nic0lette** [comment]
I considered it! I wasn't sure if people would rather see how to use the Cast SDK directly, or if using the ExoPlayer extension was more meaningful.

What do you think?
Directly use the Cast SDK: 😄
Use the ExoPlayer Cast Extension: 🎉
