### ISSUE TITLE
How to synchronize the exoplayer song duration with seekbar 

### ISSUE THREAD

**Issue by kanivel** [android/uamp#234]
Hi,
     In this code we only have play and pause events.how to integrate seekbar and how to synchronise the song duration with seekbar.

**Comment by ReckeDJ** [comment]
Would like to see this implemented!

**Comment by NathanSass** [comment]
Agreed! I would like to see this implemented or explained.

**Comment by stillac** [comment]
Agreed! I would like to see this implemented.

**Comment by nic0lette** [comment]
I think this was added in [this change](https://github.com/android/uamp/commit/8be17f94b0fe4d2be2fbfe1646b700acd8043c37), so I'll close this FR.
