### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by ramonalmeida** [android/uamp#238]
Olá.

Estou recebendo o erro java.lang.RuntimeException, na classe MusicService linha 234 (mCastSessionManager = CastContext.getSharedInstance(this).getSessionManager()) conforme imagem em anexo. O curioso é que isso ocorre somente em aparelhos Huawei e em versões Android 8.0 e 8.1. Pesquisei a respeito mas não encontrei nada de solução e estou tento muitos erros no console Android. Poderia ajudar, por favor. Obrigado.
![erroplayer](https://user-images.githubusercontent.com/41294201/43144763-48f4bec4-8f34-11e8-9536-e524ac8302c3.png)

**Comment by dturner** [comment]
Sorry we can only accept bug reports in English.
