### ISSUE TITLE
notification issue

### ISSUE THREAD

**Issue by redsparktest** [android/uamp#246]
In universal player when we play song notification is came,but many time we saw that previous and next icon are comming two times in notification.
![play_icon](https://user-images.githubusercontent.com/42539051/44336253-85b2c200-a494-11e8-83e8-05764875cb77.png)

so can we reolved it?????

**Comment by nic0lette** [comment]
Can you provide more detail as to when this is happening? What version of the code (v1/Java or master/Kotlin), OS/device details?

Thank you.

**Comment by redsparktest** [comment]
version of the code : native android applications 
os : above all vesions of lolipop
when playing song through application that time bydefault playing song also shown in notification bar . In that notification bar this issue shown

**Comment by nic0lette** [comment]
You see this issue when running the Kotlin code without modifications?

**Comment by Shiuend** [comment]
if you use branch v1, try remove `addActions()` below `fetchBitmapFromURLAsync()`. its work with me.
`public class MediaNotificationManager extends BroadcastReceiver {`
            `private void fetchBitmapFromURLAsync(...........) {`
                       ` builder.setLargeIcon(bitmap);`
                       `addActions(builder); //Remove this line`
                       `mNotificationManager.notify(NOTIFICATION_ID, builder.build());`

**Comment by redsparktest** [comment]
Thank u so much...It's working for me
Your help is really appreciated..
