### ISSUE TITLE
crash when resuming playback and app is in background

### ISSUE THREAD

**Issue by loki666** [android/uamp#252]
Fatal Exception: java.lang.IllegalStateException
Not allowed to start service Intent { cmp=net.volcanomobile.airsonicplayer/.service.MusicService }: app is in background uid UidRecord{974a95d u0a293 LAST bg:+1m47s496ms idle change:cached procs:1 seq(149,149,149)}

https://github.com/googlesamples/android-UniversalMusicPlayer/blob/d56268abb26a81d1be4659a052816f05f2a44ac4/media/src/main/java/com/example/android/uamp/media/MusicService.kt#L310

should be
```
ContextCompat.startForegroundService(applicationContext, Intent(applicationContext, this@MusicService.javaClass))
```

**Comment by dturner** [comment]
Almost certainly obsolete.
