### ISSUE TITLE
View overlap if back into the app from notification click ,

### ISSUE THREAD

**Issue by HirayClay** [android/uamp#263]
this is my operation : 
click Genres ->click Rock -> click a  song and play it-> click Home button make app background ->
click notification and back into the app , now i  continue clicking the navgation back icon and view overlap happened . this is the screenshot:
![screenshot_20190118-090012](https://user-images.githubusercontent.com/12825256/51358951-78136e00-1b00-11e9-84f0-b70d606407e6.jpg)

**Comment by dturner** [comment]
Unable to reproduce.
