### ISSUE TITLE
mediaId is empty

### ISSUE THREAD

**Issue by redsparktest** [android/uamp#267]
get error in MediaBrowserFragment in mMediaId

  MediaBrowserCompat mediaBrowser = mMediaFragmentListener.getMediaBrowser();
        mediaBrowser.getItem(mMediaId, new MediaBrowserCompat.ItemCallback() {
            @Override
            public void onItemLoaded(MediaBrowserCompat.MediaItem item) {
                mMediaFragmentListener.setToolbarTitle(
                        item.getDescription().getTitle());
            }
        });
    }

**Comment by dturner** [comment]
Fixed.
