### ISSUE TITLE
How to get duration if can not get from server in new version of UMP ? 

### ISSUE THREAD

**Issue by mnk98** [android/uamp#278]
Previously we was getting duration from LocalPlayback file but now we don't have that file to get duration
and how we can get complete status of audio play

**Comment by xyz-fly** [comment]
oh, I see the duration in MediaMetadataCompat
so, try it~

**Comment by Johnnycxq** [comment]
Hi guys,
Try it as below:

duratime = metadata.getLong(MediaMetadata.METADATA_KEY_DURATION);
