### ISSUE TITLE
App crash after stopping playback from and dismissing notification

### ISSUE THREAD

**Issue by AlAskalany** [android/uamp#283]
### How to reproduce?

1. Play a song by opening its details screen
2. From the app's notification, **pause** and **dismiss** the notification
3. Go back to the main screen
4. Tap on **Recommended** or **Albums**

### Expected

Recommended or Albums screens should open normally.

### What happens?

App crashes when attempting to open the Recommended or Albums screens.

**Comment by dturner** [comment]
Should now be fixed with https://github.com/android/uamp/pull/356.
