### ISSUE TITLE
android.app.ServiceConnectionLeaked

### ISSUE THREAD

**Issue by xyz-fly** [android/uamp#291]
The message like this:
android.app.ServiceConnectionLeaked: Activity cn.com.xxx.app.MainActivity has leaked ServiceConnection android.media.browse.MediaBrowser$MediaServiceConnection@975d1 that was originally bound here

play music in NowPlayingFragment and show notification in status-bar,  when I kill the app, then launch app again...  so, it happen the crash...

**Comment by dturner** [comment]
Cannot reproduce. Please reopen a new issue with a full bug report if you are still experiencing this issue.
