### ISSUE TITLE
Pagination from Server side and client side both

### ISSUE THREAD

**Issue by mitsdesai73** [android/uamp#301]
I have a situation where I need to apply pagination from the client-side and server-side. With every request, we'll get only 10 songs and on scrolling, you will get another 10 songs. So, how can we handle this case scenario? Please help me out. Thanks

**Comment by dturner** [comment]
This is a complicated question, which isn't specific to UAMP. I'd suggest asking it on StackOverflow. 

You may also want to check out the Paging 3 library: https://developer.android.com/topic/libraries/architecture/paging/v3-overview
