### ISSUE TITLE
Google Assistant fails to play tracks in UAMP in Android Auto 

### ISSUE THREAD

**Issue by naugehyde** [android/uamp#306]
Phone: Pixel 3a
Android Version: 10
Android Auto Ver: 4.7.593824
Google Assistant Ver: 10.83.10.21.arm64

Steps to recreate:
1) Compile and install UAMP
2) Open Android Auto
3) Ask Google "play [track*] on UAMP"

Response: 
1) Google Assistant responds "Okay, asking UAMP to play [track]"
2) UAMP app is foregrounded
3) Google Assistant responds "Sorry. Something went wrong please try opening the app to continue."
4) Track does not play.

I've tried rebooting the phone, removing and reinstalling UAMP, turning off debugging, reinstalling Android Auto. All to no avail. Same result.

On vanilla Android (not Android Auto) Google Assistant will open the app and play the track as requested.

I'm using UAMP to guide my coding on an Android Auto-capable music player. If UAMP is not an up to date guide for programming media player voice interactions, is a better (ie working) one available?

*I used: "Jazz in Paris" one of the sample tunes available on UAMP. The problem can be recreated with any track name.

**Comment by naugehyde** [comment]
Ah ha!

Found the magic cookie. The app's AndroidManifest.xml needs to include the search media intent in the MainActivity:

            <intent-filter>
                <action android:name="android.media.action.MEDIA_PLAY_FROM_SEARCH" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

UAMP's search by voice thru Google Assistant WAS working sometime in the last month but updates killed it.

I'm guessing at some point the MediaBrowserService intent was sufficient to get Google Assistant to open the app and call the appropriate search method. Clearly, that's no longer the case.

**Comment by naugehyde** [comment]
After further review... 

This appears to be an edge case. Not sure what's going on. The "fix" mentioned above may have worked but it worked for mysterious reasons. Of note, is that I had disabled Google Play Music.

**Comment by grblaine** [comment]
This is happening as well with current Spotify install. One difference though in my Android Auto testing in a new RAM. It says "Sorry. Something went wrong please try opening the app to continue.", but Spotify does play without issue. Only happens from Google Assistant.

**Comment by dturner** [comment]
Should've been fixed in #405
