### ISSUE TITLE
onPlaybackStateChanged：getPosition exception

### ISSUE THREAD

**Issue by Johnnycxq** [android/uamp#313]
I try to get current position in onPlaybackStateChanged, i found that onPlaybackStateChanged method is not executed in real time, but is executed every two seconds，causing the current playback progress interval I get to be 2 seconds.

How to get current position in real time ？？？

**Comment by Johnnycxq** [comment]
![image](https://user-images.githubusercontent.com/20370611/71499060-e2e53180-2899-11ea-8629-934f4d125f0d.png)

**Comment by Johnnycxq** [comment]
the log as below: checking the remainingSeconds value.
method: timestampToMSS; number: 63---->totalSeconds= 2, minutes= 0, remainingSeconds= 2
method: timestampToMSS; number: 63---->totalSeconds= 4, minutes= 0, remainingSeconds= 4
method: timestampToMSS; number: 63---->totalSeconds= 6, minutes= 0, remainingSeconds= 6
method: timestampToMSS; number: 63---->totalSeconds= 8, minutes= 0, remainingSeconds= 8

**Comment by dturner** [comment]
Working as intended. This is only triggered when the playback service reports a state change.
