### ISSUE TITLE
I want to pass my own list but I cant find proper way ,because you have all things depended on every other class,Can you please guide me for that?

### ISSUE THREAD

**Issue by richanshah** [android/uamp#322]

**Comment by nic0lette** [comment]
The list of songs is specified by a remote JSON file. The URL for that file is located inside [MusicService](https://github.com/android/uamp/blob/eaa9849b2043e28a4a7f9c0bd3e8a07ad38154fc/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L98-L99).

The JSON file itself is here: https://storage.googleapis.com/uamp/catalog.json

If you create your own JSON file that has that same structure, and change the URL in `MusicService`, then it will use your music. :)

**Comment by richanshah** [comment]
No I don't have json ,I have to pass dynamic list

**Comment by abolfazlkalamati** [comment]
how can pass my List from other module to MusicService in commone module ?

**Comment by richanshah** [comment]
well we have implemennted this ,for that you have to pass list instead of json in load method of jsonsource and also updatelist method whenever you want to update list

**Comment by makkhay** [comment]
@richanshah  I am trying to figure out how to pass a custom dynamic URL from my fragment or activity. How can I do that?

**Comment by linhttbk** [comment]
I think you need custom your own model that could convert into MediaMetadataCompat. Then you can you TransportControls to send custom action to the service such as removeItemFromQueue()....
Here is an example: 
`   fun prepareQueue(media: Media, playlist: List<Media>) {
        val jsonPlaylist = Gson().toJson(playlist)
        val bundle = Bundle()
        bundle.putString(KEY_PLAYLIST, jsonPlaylist)
        bundle.putString(KEY_TITLE, media.title)
        bundle.putString(KEY_PATH, media.path)
        transportControls?.prepareFromMediaId(media.id, bundle)
    }`

**Comment by ZakLiml** [comment]
> @abolfazlkalamati well we have implemennted this ,for that you have to pass list instead of json in load method of jsonsource and also updatelist method whenever you want to update list

Could I refer to your code?

**Comment by RajasekarGovindaraj** [comment]
is it possible to embedded the specific file from Youtube content directly ?

**Comment by dturner** [comment]
Please ask coding questions on StackOverflow.
