### ISSUE TITLE
If I change remoteJsonSource to custom .json file, getting a wifi screen

### ISSUE THREAD

**Issue by saireddyk** [android/uamp#336]
I changed remoteJsonSource to custom .json file to load custom album and it used to work in the old app but now its not working. I am getting wifi not available screen as if network is not available. 
Can anyone please help on how to resolve this issue ?
![Screenshot_1583724704](https://user-images.githubusercontent.com/7727290/76180863-78dfe700-617c-11ea-8fa8-4e53fe5085e1.png)

**Comment by matteodamico** [comment]
It could happen if your JSON file is not available..Are you sure that the file is reachable by https connection?

**Comment by saireddyk** [comment]
my JSON file is available and accessible and I can access the JSON content over the browser without any issue but when I use in UAMP application, I am getting above error. Can you please try with any custom JSON file so that you will notice the issue ?

**Comment by matteodamico** [comment]
Starting with Android 9 (API level 28), cleartext support is disabled by default. So it has to be available by https, not http. Otherwise, you have to add some permission in the manifest file. Have a look here https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

**Comment by saireddyk** [comment]
@matteodamico thank you for the link. I followed this https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted and resolved the issue.
