### ISSUE TITLE
Proper usage of PlayerNotificationManager

### ISSUE THREAD

**Issue by abdurahmanadilovic** [android/uamp#337]
I am currently developing a podcast player app that has a similar structure to this app. My player service looks very similar to the MusicService class in the common package but since I am using the latest exoplayer version it comes with a [PlayerNotificationManager](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerNotificationManager.html). It has a callback that can be used to display a notification for the player service. So I have two questions regarding the uamp implementation of the music service:

1. [MusicServiceConnection](https://github.com/android/uamp/blob/master/common/src/main/java/com/example/android/uamp/common/MusicServiceConnection.kt) is binding to the MusicService when the app starts. This will create the MusicService and keep ti alive as long as the app is running. This service is then upgraded to a foreground service when the ExoPlayer state changes to playing. Can I just rely on PlayerNotificationManager and start my player service as a foreground service in the onNotificationPosted callback?
2. If there any harm in removing the isForeground flag and just calling startForegroundService multiple times? From what I have read, calling startForegroundService multiple times will just call onStartCommand multiple times which is fine for me, I did not override that method, I do all the setup in onCreate in my player service.

This is the code I am using to start / stop my foreground state for my player service:

``` kotlin
object : PlayerNotificationManager.NotificationListener {
                    override fun onNotificationPosted(
                        notificationId: Int,
                        notification: Notification?,
                        ongoing: Boolean
                    ) {
                        if (ongoing) {
                            if (isForeground.not()) {
                                ContextCompat.startForegroundService(
                                    applicationContext,
                                    Intent(applicationContext, this@PlayerService.javaClass)
                                )
                                isForeground = true
                            }
                            startForeground(nowPlayingNotificationId, notification)
                        } else {
                            isForeground = false
                            stopForeground(false)
                        }
                    }

                    override fun onNotificationCancelled(
                        notificationId: Int,
                        dismissedByUser: Boolean
                    ) {
                        isForeground = false
                        stopForeground(true)
                    }
                }
```

**Comment by dturner** [comment]
> MusicServiceConnection is binding to the MusicService when the app starts. This will create the MusicService and keep ti alive as long as the app is running. This service is then upgraded to a foreground service when the ExoPlayer state changes to playing. Can I just rely on PlayerNotificationManager and start my player service as a foreground service in the onNotificationPosted callback?

Yes, that seems like the optimal approach, and that's what was intended by the `ongoing` parameter in the callback. 

> If there any harm in removing the isForeground flag and just calling startForegroundService multiple times? From what I have read, calling startForegroundService multiple times will just call onStartCommand multiple times which is fine for me, I did not override that method, I do all the setup in onCreate in my player service.

There would be no impact on your app's behaviour, however, I'd advise against running `startForegroundService` and `startForeground` multiple times successively simply because it's redundant and might cause problems in future if the API changes (for example if `startForegroundService` starts incurring any processing overhead - like `startService`).

**Comment by abdurahmanadilovic** [comment]
thanks, I think we can close this issue now.
