### ISSUE TITLE
Android Automotive OS compatibility

### ISSUE THREAD

**Issue by RajasekarGovindaraj** [android/uamp#341]
Can i use the same project file for android automotive OS (In car infotainment) ?

**Comment by nic0lette** [comment]
Yes, the Android Automotive OS specific code is part of the [**automotive**](https://github.com/android/uamp/tree/master/automotive) module.

Playback utilizes the same code as the mobile app, which is part of the [**common**](https://github.com/android/uamp/tree/master/common) module.

**Comment by mpratyush** [comment]
Please unsubscribe me from your list.

Thanks & Regards,
Pratyush
