### ISSUE TITLE
How to install it on Linux and Android?

### ISSUE THREAD

**Issue by anishmittal2020** [android/uamp#346]
Could you please list the steps required to install it on Linux (Ubuntu) and on Android? It can be less daunting to those who are new and less experienced.

**Comment by mr-shitou** [comment]
In China 
https://developer.android.google.cn/studio/projects/create-project#ImportAProject
Others 
https://developer.android.com/studio/projects/create-project#ImportAProject
plus, This project is not suitable for new learner. maybe following the android guide is better
