### ISSUE TITLE
Question about commercial use

### ISSUE THREAD

**Issue by marctan** [android/uamp#348]
Hello, 

I've created my own music player . I'm using the songs and album artwork from http://storage.googleapis.com/automotive-media/music.json. 

I'm planning to upload it to playstore for free. 

Is it ok to use the songs and resources from http://storage.googleapis.com/automotive-media/music.json?  

e.g. 
"https://storage.googleapis.com/automotive-media/Jazz_In_Paris.mp3"

**Comment by nic0lette** [comment]
Hi,

Sorry, this appears to be a question about usage rights, rather than about UAMP. I'd recommend contacting a lawyer to answer any questions you have on that front.
