### ISSUE TITLE
Android Auto (DHU): "Sorry, something went wrong. Try opening the app to continue" on verbal commands

### ISSUE THREAD

**Issue by mhelder** [android/uamp#381]
Phone: Pixel 2XL
Android Version: 10
Android Auto Version: 5.4.502264-release

Steps to recreate:

- Install and run Android Auto Desktop Head Unit emulator as [per documentation](https://developer.android.com/training/cars/testing#emulator-avd).
- Compile and install UAMP.
- Open UAMP on the DHU.
- Hit the Assistant button and ask _"Play [track]"_.
- Observe how the the Assistant responds: _"Ok, asking UAMP to play [track]"_, followed by a brief pause and then _"Sorry, something went wrong. Try opening the app to continue"_. 

This looks somewhat similar to https://github.com/android/uamp/issues/306, with the difference being that UAMP is already running. As a matter of fact, I cannot even seem to get the Assistant to pick up UAMP at all (even following the steps from https://github.com/android/uamp/issues/306 to the letter). Any verbal "play" command seems to trigger Google Play Music. Every. Single. Time.

What I did observe is that:
- UAMP play tracks just fine on the DHU when selected through the DHU's on-screen browser.
- voice commands seem to work correctly for Google Play Music, regardless of asking _"Play [track] on UAMP"_ without the app open, or _"Play [track]"_ with the app open.

Because of the _"Sorry, something went wrong"_ part, I was expecting the `UampPlaybackPreparer`'s `onPrepareFromSearch`  to yield some sort of error. To my surprise, however, it doesn't seem to be called at all? Browsing through the content and selecting a track does invoke `onPrepareFromMediaId`, but that's about it. I ended up adding breakpoints all over the media framework, but not one seems to get hit when I give the DHU a verbal command. Looking at this issues history, it seems like it did work at one point (e.g. https://github.com/android/uamp/issues/297), but going back to older UAMP snapshots doesn't seem to make a difference. Did the Assistant change? Android Auto? I'm at a loss...

What's annoying is that I've been using UAMP as reference to get Android Auto support implemented in a media app I'm working on. When I tried submitting the app as it currently stands (with the overall playback implementation nearly identical to UAMP, but without being able to validate the voice command behaviour), it got rejected saying:

```
Version(s)	Eligibility Issue
APK:xxxx	No Auto functionality
The app did not appear in the Auto screen or lens picker when we attempted to test functionality.
For example, your app does not contain an Intent filter for action “android.media.action.MEDIA_PLAY_FROM_SEARCH”.

APK:xxxx	Voice commands
Your app does not support all of the required voice commands. You can read more about how to support Voice Actions in the Android Developers Help Center.
```

But `android.media.action.MEDIA_PLAY_FROM_SEARCH` is defined on the `service` element, just like UAMP. And support for voice commands is implemented through `onPrepareFromSearch`, just like UAMP. The documentation for [Build media apps for cars](https://developer.android.com/training/cars/media) refers to UAMP a bunch of times. Same goes for [The Google Assistant and media apps](https://developer.android.com/guide/topics/media-apps/interacting-with-assistant) But somehow, something is missing or isn't quite right. And I could use a pointer on where to look for the disconnect.

// Edit: Should've maybe mentioned this: I don't have a physical car with Android Auto to test any of this on.

**Comment by orcunkobal** [comment]
Hi @mhelder 

Did you found any solution to this situation? Because today I got the same email from the play console. I added the android.media.action.MEDIA_PLAY_FROM_SEARCH in service tag as you. I think it should be between the activity tags.

**Comment by mhelder** [comment]
@orcunkobal Unfortunately, no. As you can see, I'm still waiting for a reply from Google/UAMP team on this issue. And to be honest, I have very little expectations after 2 months of total silence.

Meanwhile, we have had to temporarily put this feature on hold, pending additional information to clarify what exactly needs to be done to make a background service compatible with the Google Assistant and the Android Auto review process.

It's quite possible that `MEDIA_PLAY_FROM_SEARCH` does work when applied to an `activity`, but unfortunately that's not our use case. Our app does not have any search UI, and all we're looking for, is to bring our app's existing functionality (playing a live radio stream) to Android Auto.

**Comment by orcunkobal** [comment]
@mhelder  I understood. It seems our use cases are different from each other as you say.  I hope your problem will be done as soon as possible. The UAMP is using the intent-filter in the service tag. Other articles are saying it is related to activity tag :) Today all-day passed like that. Of course, I'll inform you about the update.

**Comment by orcunkobal** [comment]
@mhelder Hi again. The updated release accepted on the Play Store.

**Comment by nic0lette** [comment]
Hi, sorry about the delayed response. (I've been focused on supporting the [Exposure Notifications framework](https://github.com/google/exposure-notifications-internals)).

Thank you very much for raising this issue! I put in a fix based on what @orcunkobal mentioned above, and it seems to work when issuing voice commands via the Google Assistant, so I'm hopeful it also works with Android Auto. If it doesn't, please respond here and I'll reopen this/dig deeper on what's happening.

(And yes, @mhelder -- I believe things changed on the internal side, which is why it broke not only for the current version, but also past versions.)

**Comment by timusus** [comment]
I think there may also be an issue with Google's Android Auto eligibility review process.

https://issuetracker.google.com/issues/173038385
