### ISSUE TITLE
How to rename package name?

### ISSUE THREAD

**Issue by Xaninho** [android/uamp#383]
I want to rename the package name from **com.example.android.uamp** to **com.slowfy.android.uamp**, just to see if I can successfully rename the package without errors. I refactored the code successfully, including the graddle files.

However when trying to run the app, I'm getting some shell code error:

```
$ adb shell am start -n "com.example.android.uamp.next/com.slowfy.android.uamp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.example.android.uamp.next/com.slowfy.android.uamp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.android.uamp.next/com.slowfy.android.uamp.MainActivity }
Error type 3
Error: Activity class {com.example.android.uamp.next/com.slowfy.android.uamp.MainActivity} does not exist.

Error while Launching activity
```
How can I successfully rename the package name and being able to operate the app normally?

**Comment by nic0lette** [comment]
The package name is defined in the app's [`build.gradle` file here](https://github.com/android/uamp/blob/master/app/build.gradle#L25): `applicationId "com.example.android.uamp.next"`
