### ISSUE TITLE
[add-cast] Album art not displayed during cast session

### ISSUE THREAD

**Issue by dturner** [android/uamp#387]
Tested on Pixel 2 running Android 11 beta 2.5

Steps to repro: 

- Load UAMP, start playing a song
- Start a cast session, playback continues on Cast device
- Navigate the browser tree and select another song

Expected result: 

- Song details including album art is displayed in `NowPlayingFragment`

Actual result

- Album art is not displayed, and instead a placeholder image is displayed: 

![image](https://user-images.githubusercontent.com/873212/88220564-0b2fe580-cc5b-11ea-8114-df352bc87219.png)

**Comment by dturner** [comment]
As soon as I stop the cast session the album art is displayed

**Comment by AquilesCanta** [comment]
I'm able to reproduce now! Thanks.

**Comment by AquilesCanta** [comment]
I've identified the cause of the bug: When mapping `MediaMetadataCompats` to MediaSources, the mapping code modifies the `MediaMetadataCompats` by including in their `MediaDescriptionCompat` all the fields from the `MediaMetadataCompat` itself. I'll try to move this steps into the creation of the `MediaMetadataCompats` to make them more immutable-like.
