### ISSUE TITLE
[BUG] illegalstateException occurs on MusicService

### ISSUE THREAD

**Issue by Turacbey** [android/uamp#394]
All I write is about **v1 Snapshot** version. Didn't try for kotlin version.

startService which is placed on MusicService.java line 370 throws IllegalStateException on Android 8 and up.

So I tried to fix the solution trying this;

`try{
startService(new Intent(getApplicationContext(), MusicService.class));
}
catch (IllegalStateException e){
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
ContextCompat.startForegroundService(getApplicationContext(), new Intent(getApplicationContext(), MusicService.class));
}
`

It solved illegalstateException but this time, it has started to throw ANR called context.startforegroundservice() did not then call service.startforeground() for mostly Samsung devices.

Couldn't find the proper solution for it.

**Comment by nic0lette** [comment]
Sorry, the Java version is no longer being maintained. Please consider moving to the new version written in Kotlin.
