### ISSUE TITLE
Progress bar displays with no network logo when internet connection is down.

### ISSUE THREAD

**Issue by santosh-kumar-kaushal** [android/uamp#400]
Actual: Progress bar display with no network logo.

<img width="270" alt="Screenshot 2020-08-31 at 2 22 02 PM" src="https://user-images.githubusercontent.com/43371182/91701744-5bbd2b80-eb95-11ea-94fc-0827ff07cf6c.png">

Expected: Progress bar should not be shown.

**Comment by nic0lette** [comment]
Fixed with #411
