### ISSUE TITLE
Stuck on "loading content" with Android Automotive OS

### ISSUE THREAD

**Issue by swildermann** [android/uamp#409]
I tried to run uamp on android automotive OS. After deploying and launching the application on an Android Automotive OS emulator, I only see the message "loading content". Nothing else happens after that. 

Did neither work with the default Automotive emulator image nor with the Polestar 2 image. 

Internet connection on the emulator is working. I am able to play music/podcasts from other media apps which have been installed through the PlayStore.

**Comment by gurpriyabhatia** [comment]
Hi -  Is. there a fix for this issue yet? Struggling a lot to get this running on the Android Automotive OS emulator.

**Comment by dturner** [comment]
This should be fixed with https://github.com/android/uamp/pull/426. Please could you verify that this works for you.

**Comment by gurpriyabhatia** [comment]
This works. Thanks!

**Comment by gurpriyabhatia** [comment]
Hello! The loading content error seems to be back again. The app content loads intermittently unfortunately.

**Comment by ziad-halabi9** [comment]
It happens to me every time on the second run of the app.
On a fresh install of the emulator, when I run the app, everything works fine. When I run the app a second time, the emulator shows "loading content" indefinitely. So I am forced to wipe the emulator's data and rerun it every time I want to run the app.

Please fix this as it is very impractical to develop this way. Thanks.

**Comment by developerjam** [comment]
@ziad-halabi9 : Did you ever find a workaround for this?
I am stuck with the same problem. I have reported it to Google, but no response yet.....
