### ISSUE TITLE
Do Musics have a Rating System?

### ISSUE THREAD

**Issue by Xaninho** [android/uamp#415]
Greetings! I'm wondering if each media item in UAMP has a rating system activated by default.

My basic objective is to simply make a Heart/Heartless rating system, but I can't seem to be able to change the rating system at all with `musicServiceConnection.transportControls.setRating(RatingCompat.newHeartRating(true))`.

When I log the `mediaController.ratingType` [which is supposed to retrieve the type of rating](https://developer.android.com/reference/android/media/session/MediaController#getRatingType()), I always get a 0 value that stands for RatingCompat#RATING_NONE, so the change apparently wasn't successful.

Any insights or directions on this?

**Comment by nic0lette** [comment]
Those APIs are used to request the app to heart/unheart a given media item, but it's up to the app to keep track of that rating, and set it on the media item when it's created. Unfortunately this isn't implemented in UAMP, but it should be possible to add this functionality in.

**Comment by Xaninho** [comment]
Oh thank you for the note, I was getting quite frustrated for not finding it in the code haha
Seems like I'll have to dig a bit deeper into the architecture to find the proper place to keep track of the hearted media items
