### ISSUE TITLE
How To Enable Notification SeekBar in FullGuide.md screenshot?

### ISSUE THREAD

**Issue by shmueldabomb441** [android/uamp#431]
In the [screenshot ](https://github.com/android/uamp/blob/main/docs/images/6-notification.png) in FullGuide.md, it displays a version of the notification with a SeekBar to control the position in the song. I have scrupulously searched the current code base and have not been able to find any functionality to enable that. How can I enable that in my version?

**Comment by dturner** [comment]
UAMP uses the ExoPlayer class `PlayerNotificationManager` to create the notification. By default this will include a SeekBar. The `PlayerNotificationManager` handles communication between the notification and the associated player object, so when the user moves the SeekBar the seek events are passed to the player which then updates the song position. 

In UAMP we use a wrapper `UampNotificationManager` around `PlayerNotificationManager` which adds things like caching of the album artwork. Here's the code: https://github.com/android/uamp/blob/main/common/src/main/java/com/example/android/uamp/media/UampNotificationManager.kt#L44

**Comment by dturner** [comment]
Note that your audio content must have a duration in its metadata in order for the seek bar to be enabled.

**Comment by shmueldabomb441** [comment]
Do all of the default songs have the duration attribute in their metadata?

**Comment by dturner** [comment]
Yes, they do: https://storage.googleapis.com/uamp/catalog.json.

**Comment by shmueldabomb441** [comment]
Would have been nice to know that the seekbar only appears in Android 10+!! https://developer.android.com/about/versions/10/features#media-notifications
