### ISSUE TITLE
musicServiceConnection.transportControls.setPlaybackSpeed(speed) doesn't change the speed

### ISSUE THREAD

**Issue by samardzija** [android/uamp#461]
When calling musicServiceConnection.transportControls.setPlaybackSpeed(1.5F), or whatever value I set, that doesn't change the speed of the audio. I tried to find an answer in the documentation, but I couldn't find any.

Can you help me out with this problem?

**Comment by shmueldabomb441** [comment]
Is this helpful? https://stackoverflow.com/questions/31947460/changing-playback-speed-in-exoplayer

**Comment by samardzija** [comment]
It was a different problem and the solution is described here:
https://github.com/google/ExoPlayer/issues/9509

Issue can be closed.
