### ISSUE TITLE
Grammar correction

### ISSUE THREAD

**Issue by shmueldabomb441** [android/uamp#468]
I believe correct grammar is "there are three things" not "there is three things": https://github.com/android/uamp/blob/main/app/src/main/java/com/example/android/uamp/viewmodels/MediaItemFragmentViewModel.kt#L108

**Comment by dturner** [comment]
`There's` can be used in this context. 

https://english.stackexchange.com/questions/140854/there-is-there-are-depends-on-plurality-of-the-first-list-element-or-not
